### ISSUE TITLE
New feature: Search for partial text in item

### ISSUE THREAD

**Issue by maekind** [Quang-Nhan/query-json-lite#2]
I would like to be able to search by text, not matching the whole string but partially.

Here is an example:

```json
{
    "titles": [
        {
            "title": "This is a simple title",
        },
        {
            "title": "This is a a more complex *title*",
        }
    ]
}
```

I would like to do some filtering like:

```
/titles ["simple" in title]
or
/title [title~="simple"]
```

And then result should be the matching item. In this case, **{"title": "This is a simple title",}**

Thanks by your contribution btw. It's a super usefull extension.

**Comment by Quang-Nhan** [comment]
Hi @maekind,

Thanks for trying out this extension and suggesting the search by text feature on partial matches.  

I believe this currently can be accomplished by using the existing built in function ```contains(searchString, searchFor)```. Please let me know if this is not what you are after.

---

Here are a few examples:

```
/titles/*[ contains( title, "simple") ]
```
Look for all titles' title that contain "simple" substring
 
![GetSimpleTitles](https://github.com/Quang-Nhan/query-json-lite/assets/24717125/459d0214-46b9-45ce-9955-5b4ee1b38f80)

```
/titles/*[
    not( contains( title, "simple" )  )
]
```
Look for all titles' title that does not contain "simple" substring

![GetNonSimpleTitles](https://github.com/Quang-Nhan/query-json-lite/assets/24717125/7e3f761b-99f1-42b5-8b83-111b84059270)

```
/titles/*[
    contains( title, "simple" ) 
        and
    contains( title, "random" )
]
```

Look for all titles' title that contain "simple" and "random" substrings

![GetSimpleRandomTitle](https://github.com/Quang-Nhan/query-json-lite/assets/24717125/d873a7ac-bac4-40bd-b209-fc47622e2be9)

---

**NB**: There is a known bug with this function. It will not filter if the searched child object is missing the search key.
```json
{
    "titles": [
        {
            "title": "simple title"
        },
        {
            "missingTitle": "key name is not Title"
        }
    ]
}
```
```/titles/*[ contains( title, "simple") ]``` will not yield the desired output

**Comment by maekind** [comment]
My bad! Thanks for response. I will try.
